import Player from '@vimeo/player';
// import qwerty from './01-gallery';
// import { boo, Student, bar, baz } from './01-gallery';
// qwerty();
// boo();
// bar();
// baz();
// console.log(new Student('Petro'));
// console.log(Player);
import * as data from './01-gallery';
data.bar();
console.log(new data.Student('Petya'));
console.log(data.test);
